name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer Python (VERSION CORRIGÉE)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Installer dépendances
      - name: Install dependencies
        run: |
          pip install flask flake8 pytest pytest-cov

      # 4. Linter (doit échouer au début)
      - name: Run Linter
        run: flake8 .

      # 5. Tests + Coverage (même si 0 test)
      - name: Run tests with coverage
        run: pytest -v --cov=. --cov-report=xml:coverage.xml

      # 6. SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=TOLOJANAHAR_qualimetrie
            -Dsonar.organization=tolojanahar
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      
      - name: Debug files
        run: |
          ls -R